version: "3"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: docker/php-fpm
      args:
        USER_ID: ${LOCAL_USER_ID}
        GROUP_ID: ${LOCAL_GROUP_ID}
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
        - "host.docker.internal:host-gateway"
    environment:
        PHP_IDE_CONFIG: "serverName=Docker"
        ACCOUNT_EVENT_MAX_QUEUES_COUNT: ${ACCOUNT_EVENT_MAX_QUEUES_COUNT}
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php-fpm

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
        - 'mysql:/var/lib/mysql'

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_WEB_MANAGER_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

volumes:
    mysql:
        driver: local
